### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by manuelkamp** [argosopentech/LibreTranslate-init#17]
This line:
`~/LibreTranslate/env/bin/pip install -e ~/LibreTranslate/ --no-cache-dir`

results in the following error on current git version (it worked the last year fine):
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/libretranslate/LibreTranslate
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by argosopentech** [comment]
Thanks for the bug report.

LibreTranslate recently switched from setup.py to [Hatch](https://hatch.pypa.io/latest/) which I'm guessing is causing this issue. I'll investigate.

**Comment by argosopentech** [comment]
https://github.com/argosopentech/LibreTranslate-init/commit/ac10076e90553c94289fb02faca4d7f2c1d92e78
