### ISSUE TITLE
Create a EnvironmentFile for configuring LibreTranslate

### ISSUE THREAD

**Issue by argosopentech** [argosopentech/LibreTranslate-init#19]
[SystemD supports](https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service) the EnvironmentFile field to set environment variables. The could be useful for setting [LibreTranslate arguments](https://github.com/LibreTranslate/LibreTranslate#arguments) to configure LibreTranslate.

**Comment by GeorgeFourkas** [comment]
any updates on that?
