### ISSUE TITLE
gunicorn not show all the language

### ISSUE THREAD

**Issue by seng1** [argosopentech/LibreTranslate-init#22]
gunicorn not show all the language
<img width="731" alt="libretranslate" src="https://github.com/argosopentech/LibreTranslate-init/assets/3612176/ff7dd280-ec2d-4728-851f-9cb5d441281b">

**Comment by PJ-Finlay** [comment]
The model download script probably failed or was stopped during the installation. You only have the first two languages in alphabetical order.

Try running:
```
python LibreTranslate/scripts/install_models.py
```
