### ISSUE TITLE
Illegal instruction - trap invalid opcode

### ISSUE THREAD

**Issue by rhclayto** [argosopentech/LibreTranslate-init#4]
After installation, I tried the command `~/LibreTranslate/env/bin/libretranslate`, which produced the response `Illegal instruction`. 

`dmesg` shows `[2449591.634917] traps: libretranslate[2150063] trap invalid opcode ip:7f7b4a60f13c sp:7fff66433488 error:0 in libctranslate2-e7e12a4c.so[7f7b4a596000+2d04000]`.

Any ideas where to start troubleshooting?

Ubuntu 20.04.

**Comment by PJ-Finlay** [comment]
Hmm, I haven't seen that before. Can you make a post on the [forum](https://community.libretranslate.com) or main LibreTranslate repo for more visibility?

**Comment by rhclayto** [comment]
https://github.com/LibreTranslate/LibreTranslate/issues/188
